name: publish to nuget 

on: 
  push:
    branches: [ master ]
    #tags:
    #  - "v*"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
        
      
        
      - uses: nuget/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: 'latest'
      # - name: Setup MSBuild.exe
      #   uses: warrenbuckley/Setup-MSBuild@v1
      #   env:
      #     working-directory: src/Quirco.DataPumper
      # - run: msbuild -t:restore
      #   working-directory: src/Quirco.DataPumper
          
      # - run: msbuild -t:build -p:CI=true
      #   working-directory: src/Quirco.DataPumper
      # - name: Nuget Add Source
      #   run: nuget sources Add -Name "github" -Source https://nuget.pkg.github.com/fawgv/index.json -Username fawgv -Password ${{ secrets.GITHUBTOKEN }}
      # - name: Nuget SetAPIKey
      #   run: nuget setapikey ${{ secrets.GITHUBTOKEN }} -Source "github"
      # - name: Publish the package to GitHub packages
      #   working-directory: src/Quirco.DataPumper
      #   run: nuget push bin\Debug\*.nupkg -source "github" -SkipDuplicate
